[package]
name = "pingora-stuff"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
actix-web = "4.9.0"
async-trait = "0.1.83"
bytes = "1.8.0"
clap = "4.5.20"
cmake = "0.1.51"
env_logger = "0.11.5"
log = "0.4.22"
once_cell = "1.20.2"
pingora = { version = "0.3.0", features = ["pingora-cache", "pingora-load-balancing", "pingora-proxy", "proxy"] }
pingora-core = "0.4.0"
pingora-error = "0.4.0"
pingora-http = "0.4.0"
pingora-limits = "0.4.0"
pingora-load-balancing = "0.4.0"
pingora-proxy = "0.4.0"
prometheus = "0.13.4"
serde = "1.0.214"
serde_json = "1.0.132"
serde_yaml = "0.9.34"
