[package]
name = "pingora-wasm"
version = "0.8.0"
authors = ["Aditya Dahale"]
license = "Apache-2.0"
edition = "2021"
repository = "https://github.com/Aditya-9-6/aditya-dahale-pingora"
categories = ["network-programming"]
keywords = ["proxy", "pingora", "wasm", "proxy-wasm"]
description = """
WebAssembly (Proxy-WASM) dynamic filter engine for Pingora proxy.
"""

[lib]
name = "pingora_wasm"
path = "src/lib.rs"

[dependencies]
async-trait = { workspace = true }
pingora-core = { version = "0.8.0", path = "../pingora-core", default-features = false }
pingora-proxy = { version = "0.8.0", path = "../pingora-proxy" }
pingora-error = { version = "0.8.0", path = "../pingora-error" }
pingora-http = { version = "0.8.0", path = "../pingora-http" }
wasmtime = "22.0"
bytes = { workspace = true }
http = { workspace = true }
log = { workspace = true }
anyhow = "1.0"
thiserror = "1.0"

[dev-dependencies]

[features]
default = []
