[package]
name = "pingora-lru"
version = "0.8.0"
authors = ["Yuchen Wu <yuchen@cloudflare.com>"]
license = "Apache-2.0"
edition = "2021"
repository = "https://github.com/cloudflare/pingora"
categories = ["algorithms", "caching"]
keywords = ["lru", "cache", "pingora"]
description = """
LRU cache that focuses on memory efficiency, concurrency and persistence.
"""

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html
[lib]
name = "pingora_lru"
path = "src/lib.rs"

[dependencies]
hashbrown = "0"
parking_lot = "0"
arrayvec = "0.7"
log = { workspace = true }
rand = "0.8"
tokio = { workspace = true, features = ["sync", "rt", "macros"] }
async-channel = "2"
ahash = "0"
flurry = "0.5"

[dev-dependencies]
lru = { workspace = true }
criterion = { version = "0.5", features = ["html_reports"] }
tokio = { workspace = true, features = ["rt-multi-thread", "macros", "time"] }

[[bench]]
name = "bench_linked_list"
harness = false

[[bench]]
name = "bench_lru"
harness = false

[[bench]]
name = "bench_async_lru"
harness = false
