on:
  push:
    branches:
      - master

name: Docs

jobs:
  docs:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout sources
        uses: actions/checkout@93cb6efe18208431cddfb8368fd83d5badbf9bfd # v5
        with:
          submodules: "recursive"

      - name: Install build dependencies
        run: |
          sudo apt update
          sudo apt install -y cmake libclang-dev

      - name: Install stable toolchain
        uses: dtolnay/rust-toolchain@29eef336d9b2848a0b548edc03f92a220660cdb8 # stable

      - name: Run cargo doc
        run: cargo doc --no-deps --all-features
