name: 'Close stale questions'
on:
  schedule:
    - cron: '30 1 * * *'
  workflow_dispatch:

permissions:
  issues: write
  pull-requests: write

jobs:
  stale:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/stale@v9
        with:
          stale-issue-message: 'This question has been stale for a week. It will be closed in an additional day if not updated.'
          close-issue-message: 'This issue has been closed because it has been stalled with no activity.'
          days-before-stale: -1
          days-before-issue-stale: 7
          days-before-issue-close: 1
          stale-issue-label: 'stale'
          only-issue-labels: 'question'
